//root
export const SET_PLAY_SONG = 'SET_PLAY_SONG';
export const SET_PLAY_FLAG = 'SET_PLAY_FLAG';

//module search
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const DEL_SEARCH_RESULT_ITEM = 'DEL_SEARCH_RESULT_ITEM';
export const SEL_SEARCH_RESULT_ITEM = 'SEL_SEARCH_RESULT_ITEM';
export const SEL_ALL_SEARCH_RESULT_ITEM = 'SEL_ALL_SEARCH_RESULT_ITEM';
export const DEL_ALL_SEARCH_RESULT_ITEM = 'DEL_ALL_SEARCH_RESULT_ITEM';

//module onplay
export const SET_PLAY_LIST = 'SET_PLAY_LIST';
export const SEL_PLAY_LIST_ITEM = 'SEL_PLAY_LIST_ITEM';
export const SEL_ALL_PLAY_LIST_ITEM = 'SEL_ALL_PLAY_LIST_ITEM';
export const DEL_PLAY_LIST_ITEM = 'DEL_PLAY_LIST_ITEM';
export const DEL_ALL_PLAY_LIST_ITEM = 'DEL_ALL_PLAY_LIST_ITEM';